[package]
name = "url-shortener"
version = "0.1.0"
authors = ["Soha Jin <soha@lohu.info>"]

[dependencies]
rocket = "0.3.11"
rocket_codegen = "0.3.11"
regex = "0.2"
lazy_static = "1.0.0"
dotenv = "0.11.0"
mysql = "*"
rand = "*"
